name: ci/cd
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: go build
      - name: test
        run: go test -v -cover ./...
